config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'pgbanque'          =>'home#pgbanque'
  get 'pgcompte'          =>'home#pgcompte'
  get 'pgetatcivil'       =>'home#pgetatcivil'
  get 'pggenre'           =>'home#pggenre'
  get 'pgparameter'       =>'home#pgparameter'
  get 'pgpersonnel'       =>'home#pgpersonnel'
  get 'pgservice'         =>'home#pgservice'
  get 'pgstatut'          =>'home#pgstatut'
  get 'pgtitre'           =>'home#pgtitre'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Accueil'
    @titlepageone = 'Bienvenue! Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Université des Sciences Juridiques et Politique de Bamako'
    @titlepagetwob = ''
  end

  def pgbanque
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Banque'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Banque'
  end

  def pgcompte
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Compte Bancaire'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Compte Bancaire'
  end

  def pgetatcivil
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Etat Civil'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Etat Civil'
  end

  def pggenre
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Genre'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Genre'
  end

  def pgparameter
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Parametre'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Parametrage'
  end

  def pgpersonnel
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Personnel'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Personnel'
  end

  def pgservice
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Service'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Service'
  end

  def pgstatut
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Statut'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Statut'
  end

  def pgtitre
    @titleonglet = 'iAdmin'
    @titlenavbar = 'Rubrique Titre'
    @titlepageone = 'Système Intégré de Gestion - Administration'
    @titlepagetwoa = 'Rubrique'
    @titlepagetwob = 'Titre'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- Begin header content -->
<%= render partial: 'shared/home/index/navbar' %>
<!-- End header content -->

<!-- Begin page content -->
<main role="main" class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5 text-center text-black"><%=@titlepageone %></h1>
    <h4 class="mt-2 mb-5 p-2 text-light bg-info text-center">
      <span class="glyphicon glyphicon glyphicon-education h5 text-light" aria-hidden="true"></span> <%=@titlepagetwoa %>
    </h4>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="one-tab" data-toggle="tab" href="#one" role="tab" aria-controls="one" aria-selected="true">one</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="two-tab" data-toggle="tab" href="#two" role="tab" aria-controls="two" aria-selected="false">two</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="three-tab" data-toggle="tab" href="#three" role="tab" aria-controls="three" aria-selected="false">three</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="four-tab" data-toggle="tab" href="#four" role="tab" aria-controls="four" aria-selected="false">four</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="five-tab" data-toggle="tab" href="#five" role="tab" aria-controls="five" aria-selected="false">five</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="one" role="tabpanel" aria-labelledby="one-tab">
        ...one...
        <%= render partial: 'shared/icone' %>
      </div>
      <div class="tab-pane fade" id="two" role="tabpanel" aria-labelledby="two-tab">.
        ..two...
      </div>
      <div class="tab-pane fade" id="three" role="tabpanel" aria-labelledby="three-tab">
        ...three...
      </div>
      <div class="tab-pane fade" id="four" role="tabpanel" aria-labelledby="four-tab">
        ...four...
      </div>
      <div class="tab-pane fade" id="five" role="tabpanel" aria-labelledby="five-tab">
        ...five...
      </div>
    </div>
  </div>
</main>
<!-- End page content -->

<!-- Begin footer content -->
<%= render partial: 'shared/home/index/footer' %>
<!-- End footer content -->

app/views/shared/home/index/_footer.html.erb
<!-- Begin footer content -->
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>
<!-- End footer content -->

app/views/shared/home/index/_navbar.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<%= root_path %>">
      <span class="glyphicon glyphicon glyphicon-th text-warning" aria-hidden="true"></span>
      Système Intégré de Gestion - Administration
      <span class="glyphicon glyphicon glyphicon-option-vertical text-secondary" aria-hidden="true"></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav w-100">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-user text-success" aria-hidden="true"></span> cheickhtembely@gmail.com
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href=""><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href=""><span class="glyphicon glyphicon glyphicon-off text-danger" aria-hidden="true"></span> Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">
            <span class="glyphicon glyphicon glyphicon-home text-warning" aria-hidden="true"></span> Home
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-file text-warning" aria-hidden="true"></span> Accéder
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= pgbanque_path %>"><span class="glyphicon glyphicon glyphicon-oil text-secondary" aria-hidden="true"></span> Banque</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgcompte_path %>"><span class="glyphicon glyphicon glyphicon-credit-card text-secondary" aria-hidden="true"></span> Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgetatcivil_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Etat-Civil</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pggenre_path %>"><span class="glyphicon glyphicon glyphicon-adjust text-secondary" aria-hidden="true"></span> Genre</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgpersonnel_path %>"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Personnel</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgservice_path %>"><span class="glyphicon glyphicon glyphicon-tower text-secondary" aria-hidden="true"></span> Service</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgstatut_path %>"><span class="glyphicon glyphicon glyphicon-book text-secondary" aria-hidden="true"></span> Statut</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgtitre_path %>"><span class="glyphicon glyphicon glyphicon-education text-secondary" aria-hidden="true"></span> Titre</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="">
            <span class="glyphicon glyphicon glyphicon-hand-right text-warning" aria-hidden="true"></span> <%= @titlenavbar %>
          </a>
        </li>
        <li class="nav-item ml-auto">
          <a class="nav-link text-white" href=""><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= Time.now.strftime("%d/%m/%Y") %></a>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon glyphicon-align-justify text-warning" aria-hidden="true"></span> Menus</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-plus text-success" aria-hidden="true"></span> Add. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-minus text-danger" aria-hidden="true"></span> Supp. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<%= pgparameter_path %>"><span class="glyphicon glyphicon glyphicon-cog text-secondary" aria-hidden="true"></span> Parametre</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-info-sign text-primary" aria-hidden="true"></span> About</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/home/pgbanque/_navbar.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<% root_path %>">
      <span class="glyphicon glyphicon glyphicon-th text-warning" aria-hidden="true"></span>
      Gestion Intégré de l'Administration
      <span class="glyphicon glyphicon glyphicon-option-vertical text-secondary" aria-hidden="true"></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav w-100">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-user text-success" aria-hidden="true"></span> cheickhtembely@gmail.com
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-off text-danger" aria-hidden="true"></span> Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">
            <span class="glyphicon glyphicon glyphicon-home text-warning" aria-hidden="true"></span> Home
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-file text-warning" aria-hidden="true"></span> Accéder
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= pgbanque_path %>"><span class="glyphicon glyphicon glyphicon-oil text-secondary" aria-hidden="true"></span> Banque</a>
            <a class="dropdown-item" href="<%= pgcompte_path %>"><span class="glyphicon glyphicon glyphicon-credit-card text-secondary" aria-hidden="true"></span> Compte</a>
            <a class="dropdown-item" href="<%= pgetatcivil_path %>"><span class="glyphicon glyphicon glyphicon-adjust text-secondary" aria-hidden="true"></span> Etat-Civil</a>
            <a class="dropdown-item" href="<%= pggenre_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Genre</a>
            <a class="dropdown-item" href="<%= pgpersonnel_path %>"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Personnel</a>
            <a class="dropdown-item" href="<%= pgservice_path %>"><span class="glyphicon glyphicon glyphicon-tower text-secondary" aria-hidden="true"></span> Service</a>
            <a class="dropdown-item" href="<%= pgstatut_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Statut</a>
            <a class="dropdown-item" href="<%= pgtitre_path %>"><span class="glyphicon glyphicon glyphicon-education text-secondary" aria-hidden="true"></span> Titre</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#"><span class="glyphicon glyphicon glyphicon-oil text-light" aria-hidden="true"></span> <%= @titlenavbar %></a>
        </li>
        <li class="nav-item ml-auto">
          <a class="nav-link text-white" href=""><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= Time.now.strftime("%d/%m/%Y") %></a>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon glyphicon-align-justify text-warning" aria-hidden="true"></span> Menus</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-plus text-success" aria-hidden="true"></span> Add. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-minus text-danger" aria-hidden="true"></span> Supp. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-cog text-secondary" aria-hidden="true"></span> Parametre</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-info-sign text-primary" aria-hidden="true"></span> About</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/home/pgetatcivil/_navbar.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<% root_path %>">
      <span class="glyphicon glyphicon glyphicon-th text-warning" aria-hidden="true"></span>
      Gestion Intégré de l'Administration
      <span class="glyphicon glyphicon glyphicon-option-vertical text-secondary" aria-hidden="true"></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav w-100">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-user text-success" aria-hidden="true"></span> cheickhtembely@gmail.com
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-off text-danger" aria-hidden="true"></span> Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">
            <span class="glyphicon glyphicon glyphicon-home text-warning" aria-hidden="true"></span> Home
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-file text-warning" aria-hidden="true"></span> Accéder
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= pgbanque_path %>"><span class="glyphicon glyphicon glyphicon-oil text-secondary" aria-hidden="true"></span> Banque</a>
            <a class="dropdown-item" href="<%= pgcompte_path %>"><span class="glyphicon glyphicon glyphicon-credit-card text-secondary" aria-hidden="true"></span> Compte</a>
            <a class="dropdown-item" href="<%= pgetatcivil_path %>"><span class="glyphicon glyphicon glyphicon-adjust text-secondary" aria-hidden="true"></span> Etat-Civil</a>
            <a class="dropdown-item" href="<%= pggenre_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Genre</a>
            <a class="dropdown-item" href="<%= pgpersonnel_path %>"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Personnel</a>
            <a class="dropdown-item" href="<%= pgservice_path %>"><span class="glyphicon glyphicon glyphicon-tower text-secondary" aria-hidden="true"></span> Service</a>
            <a class="dropdown-item" href="<%= pgstatut_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Statut</a>
            <a class="dropdown-item" href="<%= pgtitre_path %>"><span class="glyphicon glyphicon glyphicon-education text-secondary" aria-hidden="true"></span> Titre</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item ml-auto">
          <a class="nav-link text-white" href=""><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= Time.now.strftime("%d/%m/%Y") %></a>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon glyphicon-align-justify text-warning" aria-hidden="true"></span> Menus</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-plus text-success" aria-hidden="true"></span> Add. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-minus text-danger" aria-hidden="true"></span> Supp. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-cog text-secondary" aria-hidden="true"></span> Parametre</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-info-sign text-primary" aria-hidden="true"></span> About</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/home/pggenre/_navbar.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="<% root_path %>">
      <span class="glyphicon glyphicon glyphicon-th text-warning" aria-hidden="true"></span>
      Gestion Intégré de l'Administration
      <span class="glyphicon glyphicon glyphicon-option-vertical text-secondary" aria-hidden="true"></span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav w-100">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-user text-success" aria-hidden="true"></span> cheickhtembely@gmail.com
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-off text-danger" aria-hidden="true"></span> Logout</a>
          </div>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">
            <span class="glyphicon glyphicon glyphicon-home text-warning" aria-hidden="true"></span> Home
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon glyphicon-file text-warning" aria-hidden="true"></span> Accéder
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="<%= pgbanque_path %>"><span class="glyphicon glyphicon glyphicon-oil text-secondary" aria-hidden="true"></span> Banque</a>
            <a class="dropdown-item" href="<%= pgcompte_path %>"><span class="glyphicon glyphicon glyphicon-credit-card text-secondary" aria-hidden="true"></span> Compte</a>
            <a class="dropdown-item" href="<%= pgetatcivil_path %>"><span class="glyphicon glyphicon glyphicon-adjust text-secondary" aria-hidden="true"></span> Etat-Civil</a>
            <a class="dropdown-item" href="<%= pggenre_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Genre</a>
            <a class="dropdown-item" href="<%= pgpersonnel_path %>"><span class="glyphicon glyphicon glyphicon-user text-secondary" aria-hidden="true"></span> Personnel</a>
            <a class="dropdown-item" href="<%= pgservice_path %>"><span class="glyphicon glyphicon glyphicon-tower text-secondary" aria-hidden="true"></span> Service</a>
            <a class="dropdown-item" href="<%= pgstatut_path %>"><span class="glyphicon glyphicon glyphicon-tent text-secondary" aria-hidden="true"></span> Statut</a>
            <a class="dropdown-item" href="<%= pgtitre_path %>"><span class="glyphicon glyphicon glyphicon-education text-secondary" aria-hidden="true"></span> Titre</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item ml-auto">
          <a class="nav-link text-white" href=""><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <%= Time.now.strftime("%d/%m/%Y") %></a>
        </li>
        <li class="nav-item dropdown ml-auto">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon glyphicon-align-justify text-warning" aria-hidden="true"></span> Menus</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-plus text-success" aria-hidden="true"></span> Add. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-minus text-danger" aria-hidden="true"></span> Supp. Compte</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-cog text-secondary" aria-hidden="true"></span> Parametre</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#"><span class="glyphicon glyphicon glyphicon-info-sign text-primary" aria-hidden="true"></span> About</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>